services:
<<<<<<< HEAD
<<<<<<< HEAD
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "cd app && 
              python main.py"

    container_name: "scanner-backend"
    networks:
      - scanner-network
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis


  redis:
    image: "redis:alpine"
    container_name: "scanner-redis"
    networks:
      - scanner-network
    ports:
      - "6379:6379"

networks:
  scanner-network:
    external: true

=======
=======
>>>>>>> 38aa2aa (Implement scanner webhook response and update schemas; configure Docker and docker-compose for backend service)
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: shieldstat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shieldstat
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shieldstat"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - shieldstat
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 5s

  backend:
    build: .
    container_name: shieldstat-backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:admin@postgres:5432/shieldstat
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: 7109f3e59be30049a1641006e26f81d2294642a6885768f25af549b110efa867014bc30edb96b9547e9efb01cc70e8a7485a913499f5c65c09eb1ef30463f126
    networks:
      - shieldstat
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

networks:
  shieldstat:
    driver: bridge

volumes:
  postgres_data:
<<<<<<< HEAD
>>>>>>> d8493e6 (dockerfile and docker-compose setup)
=======
=======
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "cd app && 
              python main.py"

    container_name: "scanner-backend"
    networks:
      - scanner-network
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis


  redis:
    image: "redis:alpine"
    container_name: "scanner-redis"
    networks:
      - scanner-network
    ports:
      - "6379:6379"

networks:
  scanner-network:
    external: true

>>>>>>> d9b4b4e (Implement scanner webhook response and update schemas; configure Docker and docker-compose for backend service)
>>>>>>> 38aa2aa (Implement scanner webhook response and update schemas; configure Docker and docker-compose for backend service)
