services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "cd app && 
              python main.py"

    container_name: "scanner-backend"
    networks:
      - scanner-network
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis


  redis:
    image: "redis:alpine"
    container_name: "scanner-redis"
    networks:
      - scanner-network
    ports:
      - "6379:6379"

networks:
  scanner-network:
    external: true

